#!/usr/bin/env python3
"""
Example script for reading Widom insertion binary log files.

This script demonstrates how to read and analyze the binary log file
generated by Widom insertion simulations, and how to convert the
trajectory data back to CIF or XYZ format.
"""

from mlip_mc import read_widom_binary_log
from ase.io import write
from pathlib import Path

# Read the Widom log file
data = read_widom_binary_log('results/log_widom.bin')

print(f"Total valid insertions: {len(data)}")
print()

# Access the data
for i, record in enumerate(data):
    print(f"Valid insertion {i+1} (Trial {record['trial']}): "
          f"E_ads={record['adsorption_energy']:.4f} eV, "
          f"E_total={record['total_energy']:.4f} eV")
    
    # Access the atomic structure if needed
    atoms = record['atoms']
    print(f"  Structure: {len(atoms)} atoms, formula: {atoms.get_chemical_formula()}")
    
    # Only print first 5 for brevity
    if i >= 4:
        print(f"\n... and {len(data) - 5} more valid insertions")
        break

print()
print("=" * 70)
print("Converting Trajectory to Files")
print("=" * 70)

# Create output directory for converted trajectories
output_dir = Path('results/widom_trajectories')
output_dir.mkdir(exist_ok=True, parents=True)

# Save all structures as a single XYZ trajectory file
print("\nSaving all structures as a single XYZ trajectory file...")
traj_xyz = output_dir / 'widom_trajectory.xyz'
all_atoms = [record['atoms'] for record in data]
write(str(traj_xyz), all_atoms)
print(f"  Saved: {traj_xyz} ({len(data)} structures)")

# Save all structures as a single CIF trajectory file
print("\nSaving all structures as a single CIF trajectory file...")
traj_cif = output_dir / 'widom_trajectory.cif'
write(str(traj_cif), all_atoms)
print(f"  Saved: {traj_cif} ({len(data)} structures)")

print(f"\nAll trajectory files saved to: {output_dir}/")

print()
print("=" * 70)
print("Summary Statistics")
print("=" * 70)

if len(data) > 0:
    import numpy as np
    
    adsorption_energies = [r['adsorption_energy'] for r in data]
    total_energies = [r['total_energy'] for r in data]
    
    print(f"Number of valid insertions: {len(data)}")
    print(f"Average adsorption energy: {np.mean(adsorption_energies):.4f} eV")
    print(f"Std dev adsorption energy: {np.std(adsorption_energies):.4f} eV")
    print(f"Min adsorption energy: {np.min(adsorption_energies):.4f} eV")
    print(f"Max adsorption energy: {np.max(adsorption_energies):.4f} eV")
    print(f"Average total energy: {np.mean(total_energies):.4f} eV")
    
    # Calculate Boltzmann-weighted average (Widom insertion heat of adsorption)
    # Assuming temperature from the simulation (you may need to adjust this)
    from ase.units import kB
    T = 298.0  # Kelvin - adjust if your simulation used different temperature
    beta = 1 / (kB * T)
    
    boltzmann_factors = np.exp(-beta * np.array(adsorption_energies))
    weighted_E = np.sum(np.array(adsorption_energies) * boltzmann_factors) / np.sum(boltzmann_factors)
    
    print(f"Widom adsorption energy (weighted): {weighted_E:.4f} eV")
    print(f"Average Boltzmann factor: {np.mean(boltzmann_factors):.5e}")
else:
    print("No valid insertions found in log file.")

